var namespaceresdb__driver_1_1exceptions =
[
    [ "ResdbException", "d4/df2/classresdb__driver_1_1exceptions_1_1ResdbException.html", null ],
    [ "MissingPrivateKeyError", "d4/da0/classresdb__driver_1_1exceptions_1_1MissingPrivateKeyError.html", null ],
    [ "TransportError", "d4/db4/classresdb__driver_1_1exceptions_1_1TransportError.html", "d4/db4/classresdb__driver_1_1exceptions_1_1TransportError" ],
    [ "BadRequest", "db/d86/classresdb__driver_1_1exceptions_1_1BadRequest.html", null ],
    [ "NotFoundError", "dc/d37/classresdb__driver_1_1exceptions_1_1NotFoundError.html", null ],
    [ "ServiceUnavailable", "d4/d3c/classresdb__driver_1_1exceptions_1_1ServiceUnavailable.html", null ],
    [ "GatewayTimeout", "d5/d2b/classresdb__driver_1_1exceptions_1_1GatewayTimeout.html", null ],
    [ "TimeoutError", "d7/d59/classresdb__driver_1_1exceptions_1_1TimeoutError.html", "d7/d59/classresdb__driver_1_1exceptions_1_1TimeoutError" ],
    [ "ResDBError", "de/d43/classresdb__driver_1_1exceptions_1_1ResDBError.html", null ],
    [ "ConfigurationError", "da/d34/classresdb__driver_1_1exceptions_1_1ConfigurationError.html", null ],
    [ "DatabaseAlreadyExists", "db/d2c/classresdb__driver_1_1exceptions_1_1DatabaseAlreadyExists.html", null ],
    [ "DatabaseDoesNotExist", "d0/d2a/classresdb__driver_1_1exceptions_1_1DatabaseDoesNotExist.html", null ],
    [ "StartupError", "dc/dc8/classresdb__driver_1_1exceptions_1_1StartupError.html", null ],
    [ "CyclicBlockchainError", "d3/de2/classresdb__driver_1_1exceptions_1_1CyclicBlockchainError.html", null ],
    [ "KeypairMismatchException", "de/df1/classresdb__driver_1_1exceptions_1_1KeypairMismatchException.html", null ],
    [ "OperationError", "d4/d69/classresdb__driver_1_1exceptions_1_1OperationError.html", null ],
    [ "ValidationError", "d5/d7b/classresdb__driver_1_1exceptions_1_1ValidationError.html", null ],
    [ "DoubleSpend", "d6/d36/classresdb__driver_1_1exceptions_1_1DoubleSpend.html", null ],
    [ "InvalidHash", "dc/d4f/classresdb__driver_1_1exceptions_1_1InvalidHash.html", null ],
    [ "InputDoesNotExist", "d2/d78/classresdb__driver_1_1exceptions_1_1InputDoesNotExist.html", null ],
    [ "SchemaValidationError", "d2/db9/classresdb__driver_1_1exceptions_1_1SchemaValidationError.html", null ],
    [ "InvalidSignature", "d3/de1/classresdb__driver_1_1exceptions_1_1InvalidSignature.html", null ],
    [ "TransactionNotInValidBlock", "db/d23/classresdb__driver_1_1exceptions_1_1TransactionNotInValidBlock.html", null ],
    [ "AssetIdMismatch", "d0/de3/classresdb__driver_1_1exceptions_1_1AssetIdMismatch.html", null ],
    [ "AmountError", "db/df6/classresdb__driver_1_1exceptions_1_1AmountError.html", null ],
    [ "TransactionOwnerError", "d0/d5b/classresdb__driver_1_1exceptions_1_1TransactionOwnerError.html", null ],
    [ "DuplicateTransaction", "dd/d71/classresdb__driver_1_1exceptions_1_1DuplicateTransaction.html", null ],
    [ "ThresholdTooDeep", "df/d72/classresdb__driver_1_1exceptions_1_1ThresholdTooDeep.html", null ],
    [ "GenesisBlockAlreadyExistsError", "d4/d69/classresdb__driver_1_1exceptions_1_1GenesisBlockAlreadyExistsError.html", null ],
    [ "MultipleValidatorOperationError", "d9/d62/classresdb__driver_1_1exceptions_1_1MultipleValidatorOperationError.html", null ],
    [ "HTTP_EXCEPTIONS", "d1/dce/namespaceresdb__driver_1_1exceptions.html#aff78ee2664a5b3f9ea8e3bbd8633041f", null ]
];