var graphql_2resdb__driver_2exceptions_8py =
[
    [ "resdb_driver.exceptions.ResdbException", "d4/df2/classresdb__driver_1_1exceptions_1_1ResdbException.html", null ],
    [ "resdb_driver.exceptions.MissingPrivateKeyError", "d4/da0/classresdb__driver_1_1exceptions_1_1MissingPrivateKeyError.html", null ],
    [ "resdb_driver.exceptions.TransportError", "d4/db4/classresdb__driver_1_1exceptions_1_1TransportError.html", "d4/db4/classresdb__driver_1_1exceptions_1_1TransportError" ],
    [ "resdb_driver.exceptions.BadRequest", "db/d86/classresdb__driver_1_1exceptions_1_1BadRequest.html", null ],
    [ "resdb_driver.exceptions.NotFoundError", "dc/d37/classresdb__driver_1_1exceptions_1_1NotFoundError.html", null ],
    [ "resdb_driver.exceptions.ServiceUnavailable", "d4/d3c/classresdb__driver_1_1exceptions_1_1ServiceUnavailable.html", null ],
    [ "resdb_driver.exceptions.GatewayTimeout", "d5/d2b/classresdb__driver_1_1exceptions_1_1GatewayTimeout.html", null ],
    [ "resdb_driver.exceptions.TimeoutError", "d7/d59/classresdb__driver_1_1exceptions_1_1TimeoutError.html", "d7/d59/classresdb__driver_1_1exceptions_1_1TimeoutError" ],
    [ "resdb_driver.exceptions.ResDBError", "de/d43/classresdb__driver_1_1exceptions_1_1ResDBError.html", null ],
    [ "resdb_driver.exceptions.ConfigurationError", "da/d34/classresdb__driver_1_1exceptions_1_1ConfigurationError.html", null ],
    [ "resdb_driver.exceptions.DatabaseAlreadyExists", "db/d2c/classresdb__driver_1_1exceptions_1_1DatabaseAlreadyExists.html", null ],
    [ "resdb_driver.exceptions.DatabaseDoesNotExist", "d0/d2a/classresdb__driver_1_1exceptions_1_1DatabaseDoesNotExist.html", null ],
    [ "resdb_driver.exceptions.StartupError", "dc/dc8/classresdb__driver_1_1exceptions_1_1StartupError.html", null ],
    [ "resdb_driver.exceptions.CyclicBlockchainError", "d3/de2/classresdb__driver_1_1exceptions_1_1CyclicBlockchainError.html", null ],
    [ "resdb_driver.exceptions.KeypairMismatchException", "de/df1/classresdb__driver_1_1exceptions_1_1KeypairMismatchException.html", null ],
    [ "resdb_driver.exceptions.OperationError", "d4/d69/classresdb__driver_1_1exceptions_1_1OperationError.html", null ],
    [ "resdb_driver.exceptions.ValidationError", "d5/d7b/classresdb__driver_1_1exceptions_1_1ValidationError.html", null ],
    [ "resdb_driver.exceptions.DoubleSpend", "d6/d36/classresdb__driver_1_1exceptions_1_1DoubleSpend.html", null ],
    [ "resdb_driver.exceptions.InvalidHash", "dc/d4f/classresdb__driver_1_1exceptions_1_1InvalidHash.html", null ],
    [ "resdb_driver.exceptions.InputDoesNotExist", "d2/d78/classresdb__driver_1_1exceptions_1_1InputDoesNotExist.html", null ],
    [ "resdb_driver.exceptions.SchemaValidationError", "d2/db9/classresdb__driver_1_1exceptions_1_1SchemaValidationError.html", null ],
    [ "resdb_driver.exceptions.InvalidSignature", "d3/de1/classresdb__driver_1_1exceptions_1_1InvalidSignature.html", null ],
    [ "resdb_driver.exceptions.TransactionNotInValidBlock", "db/d23/classresdb__driver_1_1exceptions_1_1TransactionNotInValidBlock.html", null ],
    [ "resdb_driver.exceptions.AssetIdMismatch", "d0/de3/classresdb__driver_1_1exceptions_1_1AssetIdMismatch.html", null ],
    [ "resdb_driver.exceptions.AmountError", "db/df6/classresdb__driver_1_1exceptions_1_1AmountError.html", null ],
    [ "resdb_driver.exceptions.TransactionOwnerError", "d0/d5b/classresdb__driver_1_1exceptions_1_1TransactionOwnerError.html", null ],
    [ "resdb_driver.exceptions.DuplicateTransaction", "dd/d71/classresdb__driver_1_1exceptions_1_1DuplicateTransaction.html", null ],
    [ "resdb_driver.exceptions.ThresholdTooDeep", "df/d72/classresdb__driver_1_1exceptions_1_1ThresholdTooDeep.html", null ],
    [ "resdb_driver.exceptions.GenesisBlockAlreadyExistsError", "d4/d69/classresdb__driver_1_1exceptions_1_1GenesisBlockAlreadyExistsError.html", null ],
    [ "resdb_driver.exceptions.MultipleValidatorOperationError", "d9/d62/classresdb__driver_1_1exceptions_1_1MultipleValidatorOperationError.html", null ],
    [ "resdb_driver.exceptions.HTTP_EXCEPTIONS", "d1/dce/namespaceresdb__driver_1_1exceptions.html#aff78ee2664a5b3f9ea8e3bbd8633041f", null ]
];